class School
  LIST = [
      { name:  "Aburi Girls Senior High " },
      { name:  "Accra Girls Senior High " },
      { name:  "Achimota Senior High " },
      { name:  "Akosombo International" },
      { name:  "Alsyd Academy" },
      { name:  "Archbishop Porter Girls Senior High" },
      { name:  "Ashesi University" },
      { name:  "Audausudai Junior High School" },
      { name:  "Bask Academy Bask Academy " },
      { name:  "Bishop Bowers School" },
      { name:  "Bishop Girl's School" },
      { name:  "Cape Coast University" },
      { name:  "Central University" },
      { name:  "Christ The King International School" },
      { name:  "Corpus Christi Catholic Basic School" },
      { name:  "East Airport International" },
      { name:  "Emit Electronic Institute" },
      { name:  "Faith Montessori" },
      { name:  "Fountainhead Christian School" },
      { name:  "Franklin & Marshall College" },
      { name:  "Ghana Christian High" },
      { name:  "Holy Child Senior High" },
      { name:  "Ideal College" },
      { name:  "Jack And Jill" },
      { name:  "Krobo Girls Senior High" },
      { name:  "Kumasi Girls' Senior High" },
      { name:  "Kwame Nkrumah University of Science and Technology" },
      { name:  "Lincoln High School" },
      { name:  "Mary Mother Of Good Counsel" },
      { name:  "Mawuli Senoir High" },
      { name:  "Methodist University" },
      { name:  "Mfantsiman Girls Senior High" },
      { name:  "Mfantsipim Senior High" },
      { name:  "Mizpah International School" },
      { name:  "Morning Glory Montessori" },
      { name:  "Morning Star" },
      { name:  "New Nation School" },
      { name:  "North Ridge Lyceum" },
      { name:  "Osu Presby Junior High School" },
      { name:  "Pentecost University" },
      { name:  "Pope John Senior High" },
      { name:  "Presbyterian Boys Senior High" },
      { name:  "Presbyterian Senior High [Osu]" },
      { name:  "Queens International School" },
      { name:  "Ridge Church School" },
      { name:  "SOS-HGIC" },
      { name:  "Soul Clinic International" },
      { name:  "St. Augustine's Senior High" },
      { name:  "St. John's Grammar" },
      { name:  "St. Mary's Senior High" },
      { name:  "St. Roses Senior High" },
      { name:  "St. Theresa's School" },
      { name:  "St. Thomas Aquinas Senior High" },
      { name:  "Tema International School" },
      { name:  "University of Ghana" },
      { name:  "University Of Ghana Basic School" },
      { name:  "Wesley Girls' Senior High" },
      { name:  "Winneba Senior High" },
      { name:  "Word Of Faith Christian School" },
      { name:  "other" }
  ]
end
